name: kyouwa
description:  あっあああああああああアアアアア

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/sericea-main
image-version: 40 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - usr: /usr # copies config/files/usr into your image's /usr.
                  # put configuration files you want in /etc/ on a booted system 
                  # in /usr/etc/ in the image. read more in files module reference.

  - type: rpm-ostree
    repos:
      # - https://copr.fedorainfracloud.org/coprs/flekz/kyouwa/repo/fedora-%OS_VERSION%/flekz-kyouwa-fedora-%OS_VERSION%.repo
      # - https://copr.fedorainfracloud.org/coprs/ryanabx/cosmic-epoch/repo/fedora-%OS_VERSION%/ryanabx-cosmic-epoch-fedora-%OS_VERSION%.repo
      # - https://copr.fedorainfracloud.org/coprs/solopasha/hyprland/repo/fedora-%OS_VERSION%/solopasha-hyprland-fedora-%OS_VERSION%.repo

      - https://copr.fedorainfracloud.org/coprs/flekz/helix-git/repo/fedora-%OS_VERSION%/flekz-helix-git-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/kylegospo/system76-scheduler/repo/fedora-%OS_VERSION%/system76-scheduler-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/alebastr/river/repo/fedora-%OS_VERSION%/alebastr-river-fedora-%OS_VERSION%.repo
    install:
      ## Environment
      - lxpolkit
      - qt6-qtwayland
      - google-noto-emoji-fonts

      - system76-scheduler

      ## Sound
      - pamixer
      - easyeffects

      # Files
      - p7zip
      - unrar-free
      - xarchiver      

      ## Japanese
      # Keyboard
      - fcitx5
      - fcitx5-mozc
      # Langpack
      - langpacks-ja
      # Text analyzing
      - mecab
      - mecab-ipadic

      ## Shell
      - alacritty
      - fish
      - ripgrep
      - eza
      # - helix
      - helix-git
      - git-delta

      ## Media
      - mpv
      - zathura
      - zathura-pdf-mupdf

      # Testing
      # - eww-wayland-git
      # - hyprland
      # Use local river
      # - river
      - river-git
      # - eww
      # - wayfire
      # - cosmic-epoch
    remove:
      # Simpler to use tty1 IMO
      - sddm
      - sddm-wayland-sway

  - type: script
    scripts:
      # - cosmic_display_manager.sh
  - type: default-flatpaks
    notify: true # Send notification after install/uninstall is finished (true/false)
    system:
      install:
      remove:

  - type: signing # this sets up the proper policy & signing files for signed images to work fully

